/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
"use strict";

systemDictionary = {
	"script-restore adapter settings": {
		en: "Adapter settings for script-restore",
		de: "Adaptereinstellungen für script-restore",
		ru: "Настройки адаптера script-restore",
		pt: "Configurações do adaptador script-restore",
		nl: "Adapterinstellingen voor script-restore",
		fr: "Paramètres de l'adaptateur script-restore",
		it: "Impostazioni adattatore script-restore",
		es: "Configuración del adaptador script-restore",
		pl: "Ustawienia adaptera script-restore",
		uk: "Налаштування адаптера script-restore",
		"zh-cn": "script-restore 适配器设置",
	},
	"backupPath": {
		en: "Backup path",
		de: "Backup-Pfad",
		ru: "Путь к резервным копиям",
		pt: "Caminho de backup",
		nl: "Back-uppad",
		fr: "Chemin de sauvegarde",
		it: "Percorso di backup",
		es: "Ruta de copia de seguridad",
		pl: "Ścieżka kopii zapasowej",
		uk: "Шлях до резервних копій",
		"zh-cn": "备份路径",
	},
	"backupPathHint": {
		en: "Directory where ioBroker backup files are stored",
		de: "Verzeichnis, in dem ioBroker-Backup-Dateien gespeichert sind",
		ru: "Каталог, в котором хранятся резервные файлы ioBroker",
		pt: "Diretório onde os arquivos de backup do ioBroker são armazenados",
		nl: "Map waar ioBroker-back-upbestanden worden opgeslagen",
		fr: "Répertoire où sont stockés les fichiers de sauvegarde ioBroker",
		it: "Directory in cui vengono archiviati i file di backup di ioBroker",
		es: "Directorio donde se almacenan los archivos de copia de seguridad de ioBroker",
		pl: "Katalog, w którym przechowywane są pliki kopii zapasowych ioBroker",
		uk: "Каталог, де зберігаються файли резервних копій ioBroker",
		"zh-cn": "存储 ioBroker 备份文件的目录",
	},
	"localEnabled": {
		en: "Enable local source",
		de: "Lokale Quelle aktivieren",
		ru: "Включить локальный источник",
		pt: "Ativar fonte local",
		nl: "Lokale bron inschakelen",
		fr: "Activer la source locale",
		it: "Abilita sorgente locale",
		es: "Activar fuente local",
		pl: "Włącz źródło lokalne",
		uk: "Увімкнути локальне джерело",
		"zh-cn": "启用本地来源",
	},
	"localSection": {
		en: "Local backup path",
		de: "Lokaler Backup-Pfad",
		ru: "Локальный путь к резервным копиям",
		pt: "Caminho de backup local",
		nl: "Lokaal back-uppad",
		fr: "Chemin de sauvegarde local",
		it: "Percorso di backup locale",
		es: "Ruta de copia de seguridad local",
		pl: "Lokalna ścieżka kopii zapasowej",
		uk: "Локальний шлях до резервних копій",
		"zh-cn": "本地备份路径",
	},
	"testConnection": {
		en: "Test connection",
		de: "Verbindung testen",
		ru: "Проверить подключение",
		pt: "Testar ligação",
		nl: "Verbinding testen",
		fr: "Tester la connexion",
		it: "Testa connessione",
		es: "Probar conexión",
		pl: "Testuj połączenie",
		uk: "Перевірити з'єднання",
		"zh-cn": "测试连接",
	},
	"smbVersionNote": {
		en: "Note: only SMB2 is supported (not SMB1 or SMB3). Enable SMB2 on your NAS/server if needed.",
		de: "Hinweis: Nur SMB2 wird unterstützt (nicht SMB1 oder SMB3). SMB2 am NAS/Server ggf. aktivieren.",
		ru: "Примечание: поддерживается только SMB2 (не SMB1 и не SMB3).",
		pt: "Nota: apenas SMB2 é suportado (não SMB1 nem SMB3).",
		nl: "Let op: alleen SMB2 wordt ondersteund (niet SMB1 of SMB3).",
		fr: "Remarque : seul SMB2 est pris en charge (pas SMB1 ni SMB3).",
		it: "Nota: è supportato solo SMB2 (non SMB1 o SMB3).",
		es: "Nota: solo se admite SMB2 (no SMB1 ni SMB3).",
		pl: "Uwaga: obsługiwany jest tylko SMB2 (nie SMB1 ani SMB3).",
		uk: "Примітка: підтримується лише SMB2 (не SMB1 і не SMB3).",
		"zh-cn": "注意：仅支持 SMB2（不支持 SMB1 或 SMB3）。",
	},
	"ftpSection": {
		en: "FTP / FTPS",
		de: "FTP / FTPS",
		ru: "FTP / FTPS",
		pt: "FTP / FTPS",
		nl: "FTP / FTPS",
		fr: "FTP / FTPS",
		it: "FTP / FTPS",
		es: "FTP / FTPS",
		pl: "FTP / FTPS",
		uk: "FTP / FTPS",
		"zh-cn": "FTP / FTPS",
	},
	"ftpEnabled": {
		en: "Enable FTP source",
		de: "FTP-Quelle aktivieren",
		ru: "Включить источник FTP",
		pt: "Ativar fonte FTP",
		nl: "FTP-bron inschakelen",
		fr: "Activer la source FTP",
		it: "Abilita sorgente FTP",
		es: "Activar fuente FTP",
		pl: "Włącz źródło FTP",
		uk: "Увімкнути джерело FTP",
		"zh-cn": "启用 FTP 来源",
	},
	"ftpHost": {
		en: "Host",
		de: "Host",
		ru: "Хост",
		pt: "Host",
		nl: "Host",
		fr: "Hôte",
		it: "Host",
		es: "Host",
		pl: "Host",
		uk: "Хост",
		"zh-cn": "主机",
	},
	"ftpPort": {
		en: "Port",
		de: "Port",
		ru: "Порт",
		pt: "Porta",
		nl: "Poort",
		fr: "Port",
		it: "Porta",
		es: "Puerto",
		pl: "Port",
		uk: "Порт",
		"zh-cn": "端口",
	},
	"ftpUser": {
		en: "Username",
		de: "Benutzername",
		ru: "Имя пользователя",
		pt: "Utilizador",
		nl: "Gebruikersnaam",
		fr: "Nom d'utilisateur",
		it: "Nome utente",
		es: "Usuario",
		pl: "Nazwa użytkownika",
		uk: "Ім'я користувача",
		"zh-cn": "用户名",
	},
	"ftpPassword": {
		en: "Password",
		de: "Passwort",
		ru: "Пароль",
		pt: "Senha",
		nl: "Wachtwoord",
		fr: "Mot de passe",
		it: "Password",
		es: "Contraseña",
		pl: "Hasło",
		uk: "Пароль",
		"zh-cn": "密码",
	},
	"ftpPath": {
		en: "Remote path",
		de: "Remote-Pfad",
		ru: "Удалённый путь",
		pt: "Caminho remoto",
		nl: "Extern pad",
		fr: "Chemin distant",
		it: "Percorso remoto",
		es: "Ruta remota",
		pl: "Ścieżka zdalna",
		uk: "Віддалений шлях",
		"zh-cn": "远程路径",
	},
	"ftpSecure": {
		en: "Use FTPS (SSL/TLS)",
		de: "FTPS verwenden (SSL/TLS)",
		ru: "Использовать FTPS (SSL/TLS)",
		pt: "Usar FTPS (SSL/TLS)",
		nl: "FTPS gebruiken (SSL/TLS)",
		fr: "Utiliser FTPS (SSL/TLS)",
		it: "Usa FTPS (SSL/TLS)",
		es: "Usar FTPS (SSL/TLS)",
		pl: "Użyj FTPS (SSL/TLS)",
		uk: "Використовувати FTPS (SSL/TLS)",
		"zh-cn": "使用 FTPS (SSL/TLS)",
	},
	"smbSection": {
		en: "SMB (Windows Share / NAS)",
		de: "SMB (Windows-Freigabe / NAS)",
		ru: "SMB (общий ресурс Windows / NAS)",
		pt: "SMB (partilha Windows / NAS)",
		nl: "SMB (Windows-share / NAS)",
		fr: "SMB (partage Windows / NAS)",
		it: "SMB (condivisione Windows / NAS)",
		es: "SMB (recurso compartido Windows / NAS)",
		pl: "SMB (udział Windows / NAS)",
		uk: "SMB (мережева папка Windows / NAS)",
		"zh-cn": "SMB（Windows 共享 / NAS）",
	},
	"smbEnabled": {
		en: "Enable SMB source",
		de: "SMB-Quelle aktivieren",
		ru: "Включить источник SMB",
		pt: "Ativar fonte SMB",
		nl: "SMB-bron inschakelen",
		fr: "Activer la source SMB",
		it: "Abilita sorgente SMB",
		es: "Activar fuente SMB",
		pl: "Włącz źródło SMB",
		uk: "Увімкнути джерело SMB",
		"zh-cn": "启用 SMB 来源",
	},
	"smbHost": {
		en: "Host / IP",
		de: "Host / IP",
		ru: "Хост / IP",
		pt: "Host / IP",
		nl: "Host / IP",
		fr: "Hôte / IP",
		it: "Host / IP",
		es: "Host / IP",
		pl: "Host / IP",
		uk: "Хост / IP",
		"zh-cn": "主机 / IP",
	},
	"smbShare": {
		en: "Share name",
		de: "Freigabename",
		ru: "Имя ресурса",
		pt: "Nome de partilha",
		nl: "Sharenaam",
		fr: "Nom du partage",
		it: "Nome condivisione",
		es: "Nombre del recurso",
		pl: "Nazwa udziału",
		uk: "Ім'я ресурсу",
		"zh-cn": "共享名称",
	},
	"smbPath": {
		en: "Path within share (optional)",
		de: "Pfad innerhalb der Freigabe (optional)",
		ru: "Путь внутри ресурса (необязательно)",
		pt: "Caminho na partilha (opcional)",
		nl: "Pad binnen share (optioneel)",
		fr: "Chemin dans le partage (optionnel)",
		it: "Percorso nella condivisione (opzionale)",
		es: "Ruta dentro del recurso (opcional)",
		pl: "Ścieżka w udziale (opcjonalnie)",
		uk: "Шлях всередині ресурсу (необов'язково)",
		"zh-cn": "共享内路径（可选）",
	},
	"smbUser": {
		en: "Username",
		de: "Benutzername",
		ru: "Имя пользователя",
		pt: "Utilizador",
		nl: "Gebruikersnaam",
		fr: "Nom d'utilisateur",
		it: "Nome utente",
		es: "Usuario",
		pl: "Nazwa użytkownika",
		uk: "Ім'я користувача",
		"zh-cn": "用户名",
	},
	"smbPassword": {
		en: "Password",
		de: "Passwort",
		ru: "Пароль",
		pt: "Senha",
		nl: "Wachtwoord",
		fr: "Mot de passe",
		it: "Password",
		es: "Contraseña",
		pl: "Hasło",
		uk: "Пароль",
		"zh-cn": "密码",
	},
	"smbDomain": {
		en: "Domain (optional)",
		de: "Domäne (optional)",
		ru: "Домен (необязательно)",
		pt: "Domínio (opcional)",
		nl: "Domein (optioneel)",
		fr: "Domaine (optionnel)",
		it: "Dominio (opzionale)",
		es: "Dominio (opcional)",
		pl: "Domena (opcjonalnie)",
		uk: "Домен (необов'язково)",
		"zh-cn": "域（可选）",
	},
};
